package com.bsz.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SAVE_INFO".
 */
@Entity
public class SaveInfo {

    @Id
    private Long id;

    @NotNull
    private String savePath;
    private long countLength;
    private long readLength;
    private int stateInte;

    @NotNull
    private String url;

    @Generated(hash = 600246954)
    public SaveInfo() {
    }

    public SaveInfo(Long id) {
        this.id = id;
    }

    @Generated(hash = 445030089)
    public SaveInfo(Long id, @NotNull String savePath, long countLength, long readLength, int stateInte,
            @NotNull String url) {
        this.id = id;
        this.savePath = savePath;
        this.countLength = countLength;
        this.readLength = readLength;
        this.stateInte = stateInte;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getSavePath() {
        return savePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSavePath(@NotNull String savePath) {
        this.savePath = savePath;
    }

    public long getCountLength() {
        return countLength;
    }

    public void setCountLength(long countLength) {
        this.countLength = countLength;
    }

    public long getReadLength() {
        return readLength;
    }

    public void setReadLength(long readLength) {
        this.readLength = readLength;
    }

    public int getStateInte() {
        return stateInte;
    }

    public void setStateInte(int stateInte) {
        this.stateInte = stateInte;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

}
